services:
    kafka:
        image: confluentinc/cp-kafka:latest
        hostname: kafka
        container_name: kafka
        ports:
            - '9092:9092'
        environment:
            CLUSTER_ID: fd5bd49a-96aa-458c-a287-1663b2db6aad
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_NODE_ID: 1
            KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_LOG_DIRS: '/var/lib/kafka/data'
            KAFKA_NUM_PARTITIONS: 1
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_MIN_INSYNC_REPLICAS: 1
            KAFKA_LOG_MESSAGE_FORMAT_VERSION: '3.0'
            KAFKA_LOG_RETENTION_HOURS: 168
            KAFKA_LOG_RETENTION_BYTES: -1
            KAFKA_LOG_SEGMENT_BYTES: 1073741824
            KAFKA_HEAP_OPTS: '-Xmx512M -Xms512M'
        volumes:
            - ./data:/var/lib/kafka/data
