services:
    kafka1:
        image: confluentinc/cp-kafka:latest
        hostname: kafka1
        container_name: kafka1
        ports:
            - '9092:9092'
            - '9093:9093'
            - '29092:29092'
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:29092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,EXTERNAL://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_LOG_DIRS: /var/lib/kafka/data
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
            KAFKA_MIN_INSYNC_REPLICAS: 2
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
            CLUSTER_ID: '6NY7bTGQQSGFZaEI-6N8dw'
        volumes:
            - /var/lib/kafka/data
        networks:
            - kraft-network

    kafka2:
        image: confluentinc/cp-kafka:latest
        hostname: kafka2
        container_name: kafka2
        ports:
            - '9094:9092'
            - '9095:9093'
            - '29094:29094'
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:29094
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,EXTERNAL://localhost:29094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_LOG_DIRS: /var/lib/kafka/data
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
            KAFKA_MIN_INSYNC_REPLICAS: 2
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
            CLUSTER_ID: '6NY7bTGQQSGFZaEI-6N8dw'
        volumes:
            - /var/lib/kafka/data
        networks:
            - kraft-network

    kafka3:
        image: confluentinc/cp-kafka:latest
        hostname: kafka3
        container_name: kafka3
        ports:
            - '9096:9092'
            - '9097:9093'
            - '29096:29096'
        environment:
            KAFKA_BROKER_ID: 3
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:29096
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092,EXTERNAL://localhost:29096
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_LOG_DIRS: /var/lib/kafka/data
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
            KAFKA_MIN_INSYNC_REPLICAS: 2
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
            CLUSTER_ID: '6NY7bTGQQSGFZaEI-6N8dw'
        volumes:
            - /var/lib/kafka/data
        networks:
            - kraft-network

    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafka-ui
        ports:
            - '8080:8080'
        environment:
            KAFKA_CLUSTERS_0_NAME: 'kraft-cluster'
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka1:9092,kafka2:9092,kafka3:9092'
        depends_on:
            - kafka1
            - kafka2
            - kafka3
        networks:
            - kraft-network

networks:
    kraft-network:
        driver: bridge
